# Generated by Django 4.0.1 on 2022-01-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starstudent',
            name='star',
            field=models.CharField(choices=[('NO_STAR', 'NO_STAR'), ('STAR', 'STAR')], default='NO_STAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='starstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_star', to='superadmin.student'),
        ),
        migrations.AlterField(
            model_name='starstudent',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_star', to='superadmin.teacher'),
        ),
    ]
