# Generated by Django 4.0.1 on 2022-01-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_starstudent_star_alter_starstudent_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starstudent',
            options={'verbose_name': 'Star Student'},
        ),
        migrations.AlterField(
            model_name='starstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_star', to='superadmin.student'),
        ),
        migrations.AlterField(
            model_name='starstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_star', to='superadmin.teacher'),
        ),
    ]
